name: CI
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  # test the code with different versions of node
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12','14','16', '17' ]
    name: Testing on Node v${{ matrix.node }}
    steps:
      # checkout the source code
      - name: Checkout Code
        uses: actions/checkout@v3.0.0

      # setup node environment
      - name: Setup Node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: ${{ matrix.node }}

      # get yarn cache directory path
      - name: Installing Dependencies (1/3 - get yarn cache path)
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      # checking / setting up the cache
      - name: Installing Dependencies (2/3 - checking/setting up cache)
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-


      # installing dependencies if cache hit fails
      - name: Installing Dependencies (3/3 - install if no cache hit)
        run: yarn install

      # test the code
      - name: Testing Code (with coverage)
        run: npm run coverage

      # upload coverage to codecov
      - name: Code Coverage
        uses: codecov/codecov-action@v2.1.0
        with:
          fail_ci_if_error: true